scc/git.py, test/integration/Sandbox.py, test/integration/test_merge.py, test/unit/test_filters.py
Replaces #186 
`git diff --name-only --diff-filter=u` is now used to find conflicting files after a failed merged.
Note f516594ec568c387225222ce258350d33b77090c adds additional checks before merging branches:
- Branch must exist (without this check non-existent branches are ignored without warning)
- Branch must share a parent commit (closes #194 )
=> Comment on possible conflicts

scc/git.py
`--diff-filter=U` should pick up **unmerged** files on all versions of git (as opposed to `-u` in git 2.2.1 which picks up everything except unmerged files, but seemed to work, presumably because the files matched some other criteria).
=> Conflict detection diff filter

.travis.yml, README.rst, setup.py
See also https://github.com/openmicroscopy/openmicroscopy/pull/3319
The following commands should work:
- ` ./setup.py test -t <path to tests>` should run a folder of tests
- `./setup.py test -t <path to tests> -s` should run a folder of tests and output any stdout with the tests to the console.
/cc @manics
=> Modify setup.py usage in Python testing

scc/git.py
A corner case, but should help if a similar situation to https://trello.com/c/QKJKaCHL/260-pr-merge-against-non-latest-homebrew-tap-fails arises in future.
To test:
- `git clone --depth=-1` a repository with open PRs (I think the PRs may need to be opened against a commit older than HEAD).
- scc merge master
You should see an exception along the lines of `Exception: Failed to find common ancestor of 52dcc56ba0155cfb10378134b9e882204d78590a and 4c77ae868536a4e614be9fbaa39c90a0df82845e`
Note I haven't bothered to make this look nice because it's a corner case, and it's mostly to help with diagnosing the underlying problem.
=> Raise exception if git merge-base returns nothing

scc/git.py
The current design was implemented for repositories with lots of open requests
in mind so that the merge branch is always updated. However, for repositories
or development branches with few PRs opened, the requirement can mean the
merge branch never gets updated to the HEAD of the development branch if all
PRs are closed or excluded.
This commit removes this restriction by pushing unconditionally the merge
branch when the --push argument is passed.
/cc @joshmoore
=> Always push the branch in the Merge command

scc/git.py, test/integration/Sandbox.py, test/integration/test_merge.py, test/unit/test_filters.py, test/unit/test_pullrequest.py
This commit fixes a regression observed in the recent integration tests where
editing a Pull Request body with an empty string seems to be a no-op. Instead,
the Sandbox method signature is modified to pass the content of the PR body and
the test first closes the existing PR and reopens a new one with an empty
description before testing the comment logic while running the merge command.
Fixes https://github.com/openmicroscopy/snoopycrimecop/issues/208
=> Allow to pass the PR description to Sandbox.open_pr()

.travis.yml, README.rst
This PR:
- adds a badge to the top-level README linking to the Pypi distribution of scc
- removes Python 2.6 from the Travis matrix build to fix the build with flake8 3+
=> Add Pypi badge and fix Travis

scc/git.py, test/unit/test_filters.py
While the filter branch functionality is working and checked by an integration test, it fails to integrate a branch called `bf_5.3.0-SNAPSHOT`. This is a deficiency in the regexp logic when identifying candidate branches.
To fix this issue, this PR extends the _parse_filters() logic to actively parse tracking branches using regular expressions. Unit tests are also added covering the range of tracking branch names.
Support is also added for branch tracking using the full Github URL similarly to what is done for Pull Request inclusion.
To test this PR:
- check the unit tests are all passing on Travis including the newly added ones
- run the [integration tests](https://ci.openmicroscopy.org/view/Failing/job/SCC-merge) and check everything is green
- for the keen ones, fork an upstream …
=> Improve tracking branch filter parsing

setup.py
Fix the new warnings flagged by the latest version of `flake8`. Travis should remain green.
=> Fix flake8 E305 error

scc/git.py, test/integration/test_merge.py
This PR is a proposal to address https://github.com/openmicroscopy/snoopycrimecop/issues/214. See the issue for more context about the application of the PR
This PR works under the current assumptions:
- the default filter semantics used for the ci-master merge builds is unchanged, i.e. all PRs considered for inclusion should be opened by a public member of the organization or labelled as `include` and neither labelled as `breaking` nor labelled as `exclude`
- developers want to have the ability to label their PRs via comments and have them deployed in isolation from the main CI
A limitation of the current implementation is that the comment labelling is tightly coupled to the users filters. This implies that for a command like `scc merge -Dnone -Ilabel`, PR comments of type `--label`
will …
=> Comment filter

scc/git.py
Addresses https://github.com/openmicroscopy/snoopycrimecop/issues/188#issuecomment-277230120
For PR which titles contains Unicode (as the ones truncated by GitHub from long commit headers), the formatting of the exclusion PRs in the log was causing UnicodeDecodeError.
No integration tests added yet. However this could be functionally tested as follows.
From a repository with open PRs containing Unicode characters in their title, force the PR(s) to be excluded and check the current version of `scc merge` is throwing an error, e.g. using the current state of https://github.com/IDR/idr-metadata, the following command should fail
```
scc merge master --info -Euser:eleanorwilliams
```
With this PR included, the same command should complete and list the excluded PRs.
=> Improve unicode handling when listing excluded PRs

.travis.yml, scc/git.py
I keep missing conflicts because they are within a visually distinct block starting "Merged PRs:" even though they are not merged.
=> report conflicting PRs in visually separate block from merges

scc/git.py
When using `scc` as a library (e.g. in scripts) it is sometimes necessary to override the github token set in gitconfig. This adds the environment variable `SCC_GITHUB_TOKEN`.
=> Read token from SCC_GITHUB_TOKEN env-var if set

scc/git.py, test/integration/test_merge.py
This prevents scc from repeatedly adding `Conflicting PR` comments in daily builds by including `--conflicts` in the comment, and only adding a comment if the last comment doesn't contain `--conflicts`. If the conflict is resolved and the last comment contained `--conflicts` then this will add a `conflict resolved` message.
The idea behind this is that up to now PRs are assumed to be included unless there is a `Conflicting PR` comment, so scc will only add `Conflict resolved` if the state changes but there is no sign of manual intervention.
=> Don't add redundant conflict comments

setup.py
https://pypi.python.org/pypi/attrs/17.3.0 mentions
Python3 and backware-incompatible changes. Trying
to restrict it after a failed Jenkins jobs:
https://ci.openmicroscopy.org/view/Failing/job/SCC-merge/933/console
=> Limit pytest<3.3 for Python 2.6 support

scc/git.py
--push is used to set the branch in `.gitmodules`.
=> git.py: Allow setting of submodule push branch

requirements.txt, scc/git.py, scc/main.py
Since there is currently no search filter for "members-only",
this loops through the given organizations, loads all team members,
and constructs a query of the form: "-author:member1 -author:member2".
=> external-issues: new command for listing non-team issues

scc/git.py
Tested in the context of the ansible-roles repository (see https://trello.com/c/ruRyhHyP/22-ansible-roles-testing), this PR contains a series of improvements to increase the scalability of `scc merge` for repositories with submodules.
- 2de5192 fixes the regexp pattern to allow `--update-gitmodules` to update URLs with or without trailing `.git`
- 625c024 inverts the pushing order, pushing submodule branches before the upstream branches. In the case of repositories with large number of submodules where branch pushing trigger builds like Travis, this prevents race conditions as the top-level repository branch could point to not-existing submodule commits
- d610888 uses the GitHub `create_fork()` API before pushing branches. If the fork exists, this should be a no-op else the fork will be …
=> Recursive merge bug fixes and improvements

scc/git.py
PyGithub 1.43 introduces a breaking change in the RateLimit API modifying both the internal representation as well as the methods of the Rate objects - see https://github.com/PyGithub/PyGithub/commit/fd8a036 and https://github.com/PyGithub/PyGithub/pull/902. This causes scc to crash when the latest version of PyGithub (currently 1.43.1) is installed.
Rather than capping PyGithub or forcing an upgrade, this PR adds backwards-compatible support for the new rate limit API with the following changes:
- the get_rate_limits() method is deprecated
- a new get_rate_limit() method forwards the calls to GitHub.get_rate_limit()
- all internal usages of rate limits are updated to use get_rate_limit. A try/exept block is added to handle older and newer version of PyGithub and return the core rate as …
=> Fix rate limiting calls following upstream API breakage

scc/git.py
Allow filtering external issues by the fact that they have no labels. Since labels can only be created by someone with write permissions, this is equivalent to having been triaged.
=> external-issues: add --no-labels

scc/git.py, test/unit/test_pullrequest.py
This change allows to use command like `update-submodules` with a YML configuration file. The use case is a job to update https://github.com/ome/bio-formats-build submodules since `bioformats` is on a different tracking branch.
Proposed tag: `0.11.0`
=> Move --repository-config to all commands acting on Git repositories

README.rst, setup.py, test/integration/Sandbox.py
All OME PyPI repos should now be pulled from the GitHub OME organization
=> Update links post organization transfer

scc/git.py, test/unit/test_githubrepository.py, test/unit/test_pullrequest.py
This change relaxes the organization check when using the `user:#org` filter so that contributions members of an organization who have not published their membership can also be whitelisted if the authenticated user is also part of the organization.
If the authenticated user is not part of the organization, then the behavior of the include filter should be identical to previously i.e. only public members will be included.
Proposed tag: `0.12.0` - although this should have minimal impact, this changes a default behavior
=> Organization membership check

scc/git.py, scc/main.py, test/unit/test_githubrepository.py, test/unit/test_pullrequest.py
The introduction of logic to couple components within super-builds (see https://github.com/ome/build-infra) has challenged the initial logic introduced in this repository where a single command was merging PRs, updating submodules and pushing to integration branches.
This PR introduces a standalone command allowing to push the state of a repository recursively to a remote branch. With it included, https://github.com/ome/build-infra/blob/1fff0fb33b55c69411e5fcaec472d4f0b635d122/recursive-merge#L43 and beyond could be more simply rewritten as:
```
scc merge $REPO_CONFIG $MERGE_OPTIONS -S $STATUS --update-gitmodules $BASE_BRANCH
echo "Update component versions"
foreach-set-dependencies
echo "Commit all component version changes"
git submodule foreach "git add -u"
git submodule foreach "git …
```
=> Push command

README.rst
The tests fail when only a global token is set.
=> Integration tests require a local not global token

README.rst, setup.py
The source code repository was renamed as scc to match the package, PyPI
distribution and command-line utility.
=> Review repository name

.travis.yml
See https://docs.travis-ci.com/user/deployment/pypi/#upload-artifacts-only-once
Proposing an immediate `0.12.1` to test the logic
=> Upload artifacts to PyPI only once

scc/git.py, scc/version.py
Collection of fixes found while working with scc under python 3.
- see: 
- see: https://stackoverflow.com/questions/33412974/how-to-uninstall-a-package-installed-with-pip-install-user
See also:
- https://github.com/ome/build-infra/pull/20 ([build 13](https://py3-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/13/))
=> Py 3 fixes

scc/git.py
In the case of mixed private/public repositories, we might still want to pass a single command which checks statuses on public repositories but ignores the status of privat repositorye.
Alternatively, we could refine the definition of the statuses to handle the private repositories case.
=> Do not check status for private repositories

scc/git.py
Rather than fetching the forks, this fetches the remote associated with the
pull request as described in https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally.
In the case of deleted forks, this should improve the robustness of the merge
command. It might also result in slight performance improvements as only the
relevant commits will be fetched as opposed to all the branches of the forks.
See also #219 which is a RFE using a similar strategy for the rebase command
=> Use GitHub Pull Request reference for merging

scc/git.py
Group issues by month so that the output can be pasted into a gist and reviewed by the team.
=> Group external-issues by month

scc/git.py, scc/main.py
Further cleanup to allow more options to be added:
```
scc external-issues
```
is now covered by:
```
scc issues             # All issues
scc issues --external  # Only non-org members
scc issues --internal  # Only org members (regardless of push rights)
```
=> Rename `external-issues` to `issues --external`

scc/git.py
dependabot adds a `dependencies` label to its PRs. Include this by default in `scc merge`
=> Include dependencies label by default

scc/git.py, test/unit/test_githubrepository.py, test/unit/test_pullrequest.py
Discovered while adding the support for the Check Suites API, our current logic makes a lot of unnecessary calls to the `Organization.has_in_members()` API to assess whether a comment has been made by a member of the organization.
This PR improves the implementation by caching the list of members when initializing the GitHub repository and reusing this list when detecting PRs. This should have no impact on the output and is mostly a performance improvement.
The easiest way to test is probably to run `scc merge --info master -vv` against an organizational repository with open PRs including comments:
- without this PR, the command output should inlude multiple GET calls to the `/orgs/<ORG>/members/<USER>` endpoint per PR
- with this PR, these should be replaced by a single top-level GET …
=> Reduce number of organization API calls

scc/git.py
See https://github.com/ome/omero-parade/pull/83#issuecomment-755209182. 
For each commit, check suites can be created by any app and it is not guaranteed all of them will fill the `conclusion` field. An example is https://api.github.com/repos/ome/omero-parade/commits/90024fdb12db958ee5ad0e750febc8ea5ddfcd9f/check-suites where the first check suite is created by the `dependabot` app  and  `conclusion` is `null`.
This updates the scc logic to only test the `conclusion` of check-suites created by the GitHub actions app, using the hardcoded app ID.
Using the `omero-parade` use-case as an example, without this PR, the dependabot PRs are all excluded with `state: None` 
```
sbesson@ls30630:omero-parade (master) $ ~/venvs/scc/bin/scc version
0.15.0
sbesson@ls30630:omero-parade (master) $ …
```
=> Only consider GitHub actions check-suites for merging

scc/git.py, test/unit/test_internal_retries.py
The latest release of [PyGithub 1.55](https://github.com/PyGithub/PyGithub/releases/tag/v1.55) changed the constructor of `GithubException` which is used for discriminating between the PyGithub and PyGithub3 libraries. The impact can be seen on https://merge-ci.openmicroscopy.org/jenkins/job/WEBSITE-push/316/console which was run quickly after the release but will affect all other push jobs.
This PR adjusts the check to use a simple import and catch and `ImportError`. This should make the library compatible with 1.55+ while keeping support for earlier versions.
The tests are adjusted to use the new constructor as per the expectation that the latest version of `PyGithub` will be used 
Proposing for an emergency `0.15.2` release
=> Fix GitHub exception constructor

scc/git.py, scc/main.py
Similar to the recent refactoring of the `issues` command, this lays the ground work to find out more about org repositories. Some (possible) examples:
=> Refactor `unsubscribed-repos` command

scc/git.py
The unauthenticated git protocol on port 9418 is no longer supported by GitHub. See https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
=> Use clone_url rather than git_url when adding remotes

scc/git.py
e.g.:
```
$ scc token
use -h to find a list of subcommands
```
This may need applying to other subcommands as well.
cc: @pwalczysko
=> scc token: suggest help if no subcommand given
